### ISSUE TITLE
Create new version

### ISSUE THREAD

**Issue by seamlink-aalves** [apache/cordova-serve#47]
Hi, it would be quite helpfull if you could create a new version after merging #44.

Everytime VSCode cordova tools gets updated I get the same error because there is no version update cordova-serve and I can no longer debug the App.

**Comment by brunolau** [comment]
Would be great if this gets released, the VS Code has to be manually patched each time when updated

**Comment by ajck** [comment]
@brunolau How do you manually patch this please?

**Comment by brunolau** [comment]
@ajck by using guide described in this post https://github.com/microsoft/vscode-cordova/issues/737#issuecomment-921894375

**Comment by seamlink-aalves** [comment]
This is a long standing issue that is already solved in the repo and just need a new version published. How can I help to create a new version?

**Comment by erisu** [comment]
@seamlink-aalves I submitted a discussion thread for preparing release version 4.0.1.

https://lists.apache.org/thread/hols7fwtd525flw53w610l01z7hkhrpb

I will attempt to get the release process going next week.

**Comment by erisu** [comment]
@seamlink-aalves [cordova-serve@4.0.1](https://www.npmjs.com/package/cordova-serve/v/4.0.1) has been released.

Since it is a patch release, a simple reinstall of the `cordova` cli should fetch the latest version.

**Comment by seamlink-aalves** [comment]
@erisu thank you for the release
